sudo: required
services:
  - docker

before_install:
  - docker build -t meira/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true meira/react-test npm test -- --coverage

after_success:
  - docker build -t meira/multi-client ./client
  - docker build -t meira/multi-nginx ./nginx
  - docker build -t meira/multi-server ./server
  - docker build -t meira/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push meira/multi-client
  - docker push meira/multi-nginx
  - docker push meira/multi-server
  - docker push meira/multi-worker


